export type VersionControlErrorCode =
  | 'SPEC_VERSION_UNSUPPORTED_FORMAT'
  | 'SPEC_VERSION_REPOSITORY_CORRUPT'
  | 'SPEC_VERSION_REPOSITORY_EXISTS'
  | 'SPEC_VERSION_INIT_FAILED'
  | 'SPEC_VERSION_NOT_INITIALIZED'
  | 'SPEC_VERSION_OBJECT_NOT_FOUND'
  | 'SPEC_VERSION_OBJECT_CORRUPT'
  | 'SPEC_VERSION_OBJECT_HASH_MISMATCH'
  | 'SPEC_VERSION_OBJECT_TYPE_MISMATCH'
  | 'SPEC_VERSION_OBJECT_TOO_LARGE'
  | 'SPEC_VERSION_OBJECT_WRITE_FAILED'
  | 'SPEC_VERSION_OBJECT_RENAME_FAILED'
  | 'SPEC_VERSION_INVALID_HASH'
  | 'SPEC_VERSION_INVALID_OBJECT'
  | 'SPEC_VERSION_CANONICAL_JSON_INVALID'
  | 'SPEC_VERSION_SYMLINK_NOT_ALLOWED'
  | 'SPEC_VERSION_SNAPSHOT_INVALID'
  | 'SPEC_VERSION_SCREEN_NOT_FOUND'
  | 'SPEC_VERSION_FEATURE_NOT_FOUND'
  | 'SPEC_VERSION_LOGICAL_PATH_CONFLICT'
  | 'SPEC_VERSION_UNSUPPORTED_FILE'
  | 'SPEC_VERSION_INDEX_NOT_FOUND'
  | 'SPEC_VERSION_INDEX_CORRUPT'
  | 'SPEC_VERSION_INDEX_CONFLICT'
  | 'SPEC_VERSION_INDEX_IN_PROGRESS'
  | 'SPEC_VERSION_INDEX_STALE'
  | 'SPEC_VERSION_INDEX_WRITE_FAILED'
  | 'SPEC_VERSION_INDEX_RENAME_FAILED'
  | 'SPEC_VERSION_HEAD_CHANGED'
  | 'SPEC_VERSION_HEAD_CORRUPT'
  | 'SPEC_VERSION_DIFF_FAILED'
  | 'SPEC_VERSION_REF_CORRUPT'
  | 'SPEC_VERSION_AUTHOR_REQUIRED'
  | 'SPEC_VERSION_AUTHOR_INVALID'
  | 'SPEC_VERSION_CONFIG_INVALID'
  | 'SPEC_VERSION_NOTHING_TO_COMMIT'
  | 'SPEC_VERSION_COMMIT_MESSAGE_INVALID'
  | 'SPEC_VERSION_COMMIT_FAILED'
  | 'SPEC_VERSION_REF_CONFLICT'
  | 'SPEC_VERSION_REF_NOT_FOUND'
  | 'SPEC_VERSION_REF_INVALID'
  | 'SPEC_VERSION_BRANCH_EXISTS'
  | 'SPEC_VERSION_BRANCH_NOT_FOUND'
  | 'SPEC_VERSION_CURRENT_BRANCH_DELETE'
  | 'SPEC_VERSION_TAG_EXISTS'
  | 'SPEC_VERSION_TAG_NOT_FOUND'
  | 'SPEC_VERSION_REVISION_NOT_FOUND'
  | 'SPEC_VERSION_REVISION_AMBIGUOUS'
  | 'SPEC_VERSION_REVISION_TYPE_MISMATCH'
  | 'SPEC_VERSION_WORKING_TREE_DIRTY'
  | 'SPEC_VERSION_CHECKOUT_FAILED'
  | 'SPEC_VERSION_CHECKOUT_TRANSACTION_INCOMPLETE'
  | 'SPEC_VERSION_REVERT_CONFLICT'
  | 'SPEC_VERSION_REVERT_UNSUPPORTED'
  | 'SPEC_VERSION_REPOSITORY_IN_PROGRESS'
  | 'SPEC_VERSION_RECOVERY_REQUIRED'
  | 'SPEC_VERSION_RECOVERY_UNSAFE'
  | 'SPEC_VERSION_FSCK_FAILED'
  | 'SPEC_VERSION_MERGE_IN_PROGRESS'
  | 'SPEC_VERSION_MERGE_NOT_IN_PROGRESS'
  | 'SPEC_VERSION_MERGE_CONFLICT'
  | 'SPEC_VERSION_MERGE_BASE_NOT_FOUND'
  | 'SPEC_VERSION_MERGE_BASE_AMBIGUOUS'
  | 'SPEC_VERSION_MERGE_DETACHED_HEAD'
  | 'SPEC_VERSION_MERGE_UNBORN_HEAD'
  | 'SPEC_VERSION_MERGE_UNRESOLVED'
  | 'SPEC_VERSION_MERGE_HEAD_CHANGED'
  | 'SPEC_VERSION_MERGE_ABORT_UNSAFE';

export class VersionControlError extends Error {
  readonly code: VersionControlErrorCode;

  constructor(code: VersionControlErrorCode, message: string) {
    super(message);
    this.name = 'VersionControlError';
    this.code = code;
  }
}

export function createVersionControlError(
  code: VersionControlErrorCode,
  message: string,
): VersionControlError {
  return new VersionControlError(code, message);
}
